version: '3.8'

services: 

  backend:
    image: joaoovittor/estudo-spring-boot
    restart: always
    build: .
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3306/estudo-spring?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: root
    command: mvn spring-boot:run
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - joao-network

  db:
    image: mysql:8.0.30
    restart: always
    environment: 
      MYSQL_DATABASE: estudo-spring
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - .dbdata:/var/lib/mysql
    ports: 
      - 3307:3306
    networks:
      - joao-network


networks:
  joao-network:
    driver: bridge
